services:
  backend:
    build: ./backend
    env_file: ./backend/.env
    environment:
      DB_HOST: host.docker.internal
      DB_SSLMODE: disable
    volumes:
      - ./backend/uploads:/app/uploads
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
    # TIDAK expose port 5000

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: /api
    restart: unless-stopped
    # TIDAK expose port 80 (nanti lewat Caddy)

  reverse_proxy:
    image: caddy:2.8-alpine
    ports:
      - "80:80"           # akses lewat http://localhost
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - ./data/caddy:/data
      - ./data/caddy_config:/config
    depends_on:
      - frontend
      - backend
    restart: unless-stopped
